exclude: "^\
  (third-party/.*)\
  "
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace # trims trailing whitespace.
      #- id: flake8 #Python checker

  #Python Formatter
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.8

  #Python Linting
  - repo: https://github.com/PyCQA/pylint
    rev: v2.15.6
    hooks:
      - id: pylint
        language_version: python3.8

  #Python checker
  #- repo: https://github.com/PyCQA/flake8
  #  rev: 5.0.4
  #  hooks:
  #    - id: flake8

  #C#/C/C++ Formatter
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.4
    hooks:
      - id: clang-format
        files: \.(cs|json|yaml)$

  #dotnet formatter
  #- repo: https://github.com/jvstein/pre-commit-dotnet-format
  #  rev: v0.2
  #  hooks:
  #    - id: dotnet-format
  #      files: \.(cs|json)$

  #Prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier

  # Js Eslint
  #- repo: https://github.com/pre-commit/mirrors-eslint
  #  rev: v8.28.0
  #  hooks:
  #    - id: eslint
  #      args: [--fix]

  # tslint
  #- repo: https://github.com/awebdeveloper/pre-commit-tslint
  #  rev: 0.0.2
  #  hooks:
  #    - id: tslint
