name: Run misspell

on: [push, pull_request]

jobs:
    check-reviewdog:
        name: Check Spelling - reviewdog
        runs-on: ubuntu-latest
        steps:
            - uses: Wandalen/wretry.action@v1.0.36
              name: Checkout
              with:
                  action: actions/checkout@v3
                  with: |
                      token: ${{ github.token }}
                  attempt_limit: 3
                  attempt_delay: 2000
            - uses: reviewdog/action-misspell@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
    check-spellcheck:
        name: Check Spelling - pyspelling
        runs-on: ubuntu-latest
        steps:
            - uses: Wandalen/wretry.action@v1.0.36
              name: Checkout
              with:
                  action: actions/checkout@v3
                  with: |
                      token: ${{ github.token }}
                  attempt_limit: 3
                  attempt_delay: 2000
            - uses: igsekor/pyspelling-any@v0.0.2
