name: Continuous Integration

# This action works with pull requests and pushes
on: workflow_dispatch

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.2

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Pretify changes
