name: Lint all Code Base
on: [push, pull_request]

jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          # Change to 'specific branch name' if your main branch differs
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Linting And Code Analyser"
          commit-message: ":art: Analyse and Lint code with Super-linter"
          body: |
            Linting has been complete with the changes applied.
          base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
          branch: actions/Lint
